---
title: "Final Project Written Description"
author: "Claire Dudley"
date: "5/9/2022"
output: html_document
---

  I created this final project as an extension of my senior honors thesis in Statistics with the overall goal of quantifying winners and losers of the NHL trade deadline. For my SYE, I created a model with two separate lines, one before and one after the trade deadline, to show how teams' trajectories and probabilities of winning a game changed throughout the season as well as after the trade deadline. The data I used was from Sports Books Reviews Online, and I used data from each season from 2016-2022 that included the date of a game, one of the teams playing, the number of goals said team scored each period and the total number of goals, opening and closing money lines, and puck lines.The response variable was the probability of the team winning the game using Vegas moneyline odds. To display my results, I had a few individually created graphs that showed two different slopes for before and after the season, but each graph took me a while to make and I had to individually code in the intercepts of lines for each team (I couldn't just use a geom_smoother as my model was a Lasso model, not a simple linear model). While I was content with my project, I knew a Shiny app where the user got to choose a season and team throughout 6 seasons (the seasons that I used data for my model) would make for a great visualization and way for people to understand what my project does. Tables showing "winners" and "losers" of a trade deadline are useful, but it is even better to be able to see how these teams are winners and losers through interactive graphs.
  
  Throughout this semester in this course, we were introduced to many concepts and principles about data visualization including topics like mapping, expressing uncertainty, and ethics. We started the class by learning about what makes figures good or bad - this can be in terms of aesthetics, the data being presented, and the way in which data is presented. I made it my goal in my Shiny app to keep the colors simple and minimal, have a clean background, and simplify my graph as much as possible (in terms of grid lines, axis marks, and legends). I used the shiny theme "yeti" which allowed for a very clean and minimalistic presentation, and used on my graph the ggtheme theme_classic so that my graph was also minimalist and easy to follow. I also made sure to use a color scheme for my scatterplot that is dark against the white background and easy to distinguish between the different groups. 
  
  While I learned a lot of concepts throughout the semester in both mapping and expressing uncertainty, these concepts weren't as applicable to my project. In terms of mapping, I did not use mapping in my project. For expressing uncertainty, the points on my graphs represent Vegas's moneyline odds, not something calculated by my model - I was seeing how Vegas's predictions changed throughout a season.
  
  Overall, if I were to continue or build off of this project I think I would be interested in investigating how often Vegas's odds are correct and possibly complaining these results to other resources used for betting. I know that Vegas odds are often the most popular, but it would be interesting to compare to see which are most accurate. Another potential direction that this project could go in would be to somehow measure or control for other impacts at the end of the season. One limitation of this project was that there are a lot of other things happening at the end of the season that impact Vegas' probabilities of a team winning, including a team having key players returning from injury, becoming injured, or even teams that have no chance at a playoff run giving up. If we could possibly rate players, we could control for when good players get hurt at the end of the season or if good players come back from injuries at the end of the season.
  